
-- HOTEL table
CREATE TABLE Hotel (
    hotelId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    address VARCHAR2(255),
    phoneNumber VARCHAR2(20),
    emailAddress VARCHAR2(100)
);

-- ROOM table
CREATE TABLE Room (
    roomId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotelId NUMBER NOT NULL,
    roomNumber VARCHAR2(20),
    roomType VARCHAR2(50),
    capacity NUMBER CHECK (capacity > 0),
    pricePerNight NUMBER(10, 2) CHECK (pricePerNight >= 0),
    CONSTRAINT fk_room_hotel FOREIGN KEY (hotelId) REFERENCES Hotel(hotelId)
);

-- BOOKING table
CREATE TABLE Booking (
    bookingId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roomId NUMBER NOT NULL,
    checkingInDate DATE,
    checkingOutDate DATE,
    bookingDate DATE DEFAULT SYSDATE,
    status VARCHAR2(50),
    CONSTRAINT fk_booking_room FOREIGN KEY (roomId) REFERENCES Room(roomId)
);

-- GUEST table
CREATE TABLE Guest (
    guestId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR2(50),
    lastName VARCHAR2(50),
    phoneNumber VARCHAR2(20),
    emailAddress VARCHAR2(100),
    address VARCHAR2(255)
);

-- BOOKINGGUEST 
CREATE TABLE BookingGuest (
    bookingGuestId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookingId NUMBER NOT NULL,
    guestId NUMBER NOT NULL,
    isPrimary NUMBER(1),  -- use 0 or 1
    CONSTRAINT fk_bookingguest_booking FOREIGN KEY (bookingId) REFERENCES Booking(bookingId),
    CONSTRAINT fk_bookingguest_guest FOREIGN KEY (guestId) REFERENCES Guest(guestId)
);

-- PAYMENT table
CREATE TABLE Payment (
    paymentId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookingId NUMBER NOT NULL,
    paymentDate DATE DEFAULT SYSDATE,
    amount NUMBER(10, 2) CHECK (amount >= 0),
    paymentMethod VARCHAR2(50),
    status VARCHAR2(50),
    CONSTRAINT fk_payment_booking FOREIGN KEY (bookingId) REFERENCES Booking(bookingId)
);
